name: "Setup Poetry"
description: "Setup the poetry environment"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
    - uses: ts-graphviz/setup-graphviz@v1
    - run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash
    - run: poetry config virtualenvs.in-project true
      shell: bash
