name: build, lint, test

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-action
      - run: poetry run black --check .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-action
      - run: poetry run pytest
