name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: ts-graphviz/setup-graphviz@v1
      - run: pip3 install poetry
      - run: poetry config virtualenvs.in-project true
      - run: poetry install
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: ts-graphviz/setup-graphviz@v1
      - run: pip3 install poetry
      - run: poetry config virtualenvs.in-project true
      - run: poetry run black --check .
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: ts-graphviz/setup-graphviz@v1
      - run: pip3 install poetry
      - run: poetry config virtualenvs.in-project true
      - run: poetry run pytest
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [lint,test]
